import Head from "next/head";
import { Footer } from "src/components/Footer";
import { Header } from "src/components/Header";
import { Main } from "src/components/Main";
import styles from "src/styles/Home.module.css";

const Home = (props) => {
  const {
    count,
    isShow,
    handleClick,
    handleDisplay,
    text,
    array,
    handleChange,
    handleAdd,
  } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />

      {isShow && <p>{count}</p>}
      <button onClick={handleClick}>ボタン</button>
      <br />
      <button onClick={handleDisplay}>{isShow ? "非表示" : "表示"}</button>

      <br />
      <input type="text" value={text} onChange={handleChange} />
      <br />
      <button onClick={handleAdd}>追加</button>
      <ul>
        {array.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ul>
      <Main page="index" />
      <Footer />
    </div>
  );
};

export default Home;
